#!/bin/bash

release=latest

dockid=$(docker ps -aq --filter "name=firefox-icedtea")

if [[ "a$dockid" == "a" ]]; then

# Run docker image
docker run --net=host \
	--env="DISPLAY" \
	--volume="$HOME/.Xauthority:/home/firefox/.Xauthority:rw" \
	--name="firefox-icedtea" \
	--interactive \
	--tty \
	--detach \
	avalitan/firefox-icedtea:$release

else
	docker start $dockid
fi
if [[ "a$1" != "a" ]]; then
	docker run $dockid /opt/firefox.sh "$1"
fi
