#!/bin/bash

release=latest

dockid=$(docker ps -aq --filter "name=firefox-icedtea")
dockact=$(docker ps -q --filter "name=firefox-icedtea")

# Run docker image
if [[ "a$dockid" == "a" ]]; then
	docker run --net=host \
		--env="DISPLAY" \
		--volume="$HOME/.Xauthority:/home/firefox/.Xauthority:rw" \
		--name="firefox-icedtea" \
		--interactive \
		--tty \
		--detach \
		avalitan/firefox-icedtea:$release
	dockid=$(docker ps -aq --filter "name=firefox-icedtea")
else
	if [[ "a$dockid" != "a$dockact" ]]; then
		docker start $dockid
	fi
fi

if [[ "a$1" != "a" ]]; then
	docker exec -it $dockid /opt/firefox.sh "$1"
fi
